// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyProductAttribute("HtmlTags.AspNet.Mvc")]
[assembly: AssemblyVersionAttribute("0.1.2")]
[assembly: AssemblyFileVersionAttribute("0.1.2.0")]
[assembly: ComVisibleAttribute(false)]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.2";
    }
}
